Now we're trying to apply the version specific patches in the COMPATXX directory

diff --git a/.github/workflows/run_unit_tests_on_docker.yml b/.github/workflows/run_unit_tests_on_docker.yml
--- a/.github/workflows/run_unit_tests_on_docker.yml
+++ b/.github/workflows/run_unit_tests_on_docker.yml
@@ -268,11 +268,11 @@ jobs:
             echo "Copying contents of $COMPAT_DIR to $SPOCK_DIR..." && \
             cp -r "$COMPAT_DIR"/* "$SPOCK_DIR" && \
             echo "Successfully copied contents of $COMPAT_DIR." && \
-            ls -la "$SPOCK_DIR"; \
           else \
-            echo "Error: Directory $COMPAT_DIR does not exist!" && exit 1; \
-            ls -la $COMPAT_DIR
-          fi
+            echo "Error: Directory $COMPAT_DIR does not exist!" && exit 1; && \
+            ls -la $COMPAT_DIR && \
+          fi && \
+          ls -la $COMPAT_DIR
         '
 
     - name: Build and Install Spock
