Changing privileges for make

diff --git a/.github/workflows/run_unit_tests_on_docker.yml b/.github/workflows/run_unit_tests_on_docker.yml
--- a/.github/workflows/run_unit_tests_on_docker.yml
+++ b/.github/workflows/run_unit_tests_on_docker.yml
@@ -280,7 +280,12 @@ jobs:
     - name: Make Spock
       run: |
         docker exec -u postgres spock bash -c "
-          source /home/postgres/.bashrc && \
+          PG_CONFIG_PATH=\$(find /usr/local/pgsql -type f -name pg_config | head -n 1) && \
+          if [ -z \"\$PG_CONFIG_PATH\" ]; then \
+            echo 'Error: pg_config not found!' && exit 1; \
+          fi && \
+          export PATH=\$(dirname \"\$PG_CONFIG_PATH\"):\$PATH && \
+          echo \"pg_config location successfully added to PATH: \$(dirname \"\$PG_CONFIG_PATH\")\" && \
           cd /home/postgres/spock-private && \
           echo 'Building Spock extension...' && \
           make
