Applying correct patches to correct repo

diff --git a/.github/workflows/run_unit_tests_on_docker.yml b/.github/workflows/run_unit_tests_on_docker.yml
--- a/.github/workflows/run_unit_tests_on_docker.yml
+++ b/.github/workflows/run_unit_tests_on_docker.yml
@@ -252,6 +252,22 @@ jobs:
           pg_config 
         "
 
+    - name: Copy COMPAT Directory for matrix.pgver
+      run: |
+        docker exec -u postgres spock bash -c "
+          cd /home/postgres/spock-private && \
+          MATRIX_PGVER=${{ matrix.pgver }} && \
+          COMPAT_DIR=COMPAT\${MATRIX_PGVER} && \
+          if [ -d \"\$COMPAT_DIR\" ]; then \
+            echo \"Copying contents of \$COMPAT_DIR to /home/postgres/spock-private...\" && \
+            cp -r \$COMPAT_DIR/* . && \
+            echo \"Successfully copied contents of \$COMPAT_DIR.\"; \
+          else \
+            echo \"Error: Directory \$COMPAT_DIR does not exist!\" && exit 1; \
+          fi
+          ls -la /home/postgres/spock-private
+        "
+
     - name: Build and Install Spock
       run: |
         docker exec -u postgres spock bash -c "
