Applying correct patches to correct repo

diff --git a/.github/workflows/run_unit_tests_on_docker.yml b/.github/workflows/run_unit_tests_on_docker.yml
--- a/.github/workflows/run_unit_tests_on_docker.yml
+++ b/.github/workflows/run_unit_tests_on_docker.yml
@@ -254,28 +254,25 @@ jobs:
 
     - name: Copy COMPAT Directory for matrix.pgver
       run: |
-        docker exec -u postgres spock bash -c "
+        docker exec -u postgres spock bash -c '
           SPOCK_DIR="/home/postgres/spock-private/" && \
           MATRIX_PGVER="${{ matrix.pgver }}" && \
           POSTGRES_DIR="/home/postgres/postgres-source" && \
 
-          echo "Spock Directory: $SPOCK_DIR"
-          echo "PostgreSQL Version: $MATRIX_PGVER"
-          echo "Postgres Source Directory: $POSTGRES_DIR"
+          echo "Spock Directory: $SPOCK_DIR" && \
+          echo "PostgreSQL Version: $MATRIX_PGVER" && \
+          echo "Postgres Source Directory: $POSTGRES_DIR" && \
 
-          ls $SPOCK_DIR
-          COMPAT_DIR=$SPOCK_DIR\COMPAT\${MATRIX_PGVER} && \
-          ls -la $SPOCK_DIR/COMPAT${MATRIX_PGVER}
-          
-          if [ -d \"\$COMPAT_DIR\" ]; then \
-            echo \"Copying contents of \$COMPAT_DIR to /home/postgres/spock-private...\" && \
-            cp -r \$COMPAT_DIR/* . && \
-            echo \"Successfully copied contents of \$COMPAT_DIR.\"; \
+          COMPAT_DIR="${SPOCK_DIR}COMPAT${MATRIX_PGVER}" && \
+          if [ -d "$COMPAT_DIR" ]; then \
+            echo "Copying contents of $COMPAT_DIR to $SPOCK_DIR..." && \
+            cp -r "$COMPAT_DIR"/* "$SPOCK_DIR" && \
+            echo "Successfully copied contents of $COMPAT_DIR." && \
+            ls -la "$SPOCK_DIR"; \
           else \
-            echo \"Error: Directory \$COMPAT_DIR does not exist!\" && exit 1; \
+            echo "Error: Directory $COMPAT_DIR does not exist!" && exit 1; \
           fi
-          ls -la /home/postgres/spock-private
-        "
+        '
 
     - name: Build and Install Spock
       run: |
