Updated output checking

diff --git a/.github/workflows/spockbench.yml b/.github/workflows/spockbench.yml
--- a/.github/workflows/spockbench.yml
+++ b/.github/workflows/spockbench.yml
@@ -50,6 +50,11 @@ jobs:
 
       - name: Check spockbench output
         run: |
-          cd ${GITHUB_WORKSPACE}/tests/
-          ./check-outputs.sh
+          bad_containers=$(docker compose ps -a --format json | jq -s '[.[] | select(.ExitCode != 0)] | length')
+
+          if [ "$bad_containers" -ne 0 ]; then
+            echo "FAIL: $bad_containers container(s) exited with non-zero code"
+            docker compose ps -a
+            exit 1
+          fi
 
